<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LeadManagement.Application\LeadManagement.Application.csproj" />
    <ProjectReference Include="..\LeadManagement.Domain\LeadManagement.Domain.csproj" />
    <ProjectReference Include="..\LeadManagement.Infra.Data\LeadManagement.Infra.Data.csproj" />
  </ItemGroup>

</Project>
